language: php
php: '7.2'

before_script: composer install

script: vendor/bin/phpunit --configuration framework/phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)